metadata:
  description: config for AQM_NA_13km, retro, on Hera
user:
  MACHINE: derecho
  ACCOUNT: NRAL0039
platform:
  WORKFLOW_MANAGER: rocoto
  # # Directory with links to mimic consolidated fix files on NOAA machines:
  # This didn't work to configure here -- had to add to machine/derecho.yaml
  #   but trying it again, because it may have alleviated the empty --src_dir argument for nexus
  # FIXaqm_sav:  /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/fix
  QUEUE_DEFAULT: main
  QUEUE_FCST: main
  QUEUE_HPSS: main
  SCHED_NATIVE_CMD: '-l job_priority=economy'
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 1
  EXPT_BASEDIR: /glade/derecho/scratch/paddy/aqm_ensemble_expt
  EXPT_SUBDIR: gfas_gefs2_nei_coldstart_0815
  PREDEF_GRID_NAME: AQM_NA_13km
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2020081512'
  DATE_LAST_CYCL:  '2020081512'
  INCR_CYCL_FREQ: 24
  FCST_LEN_HRS: 72
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  DEBUG: false
  COMPILER: intel
  DIAG_TABLE_TMPL_FN: diag_table_aqm.FV3_GFS_v16
  FIELD_TABLE_TMPL_FN: field_table_aqm.FV3_GFS_v16
  DO_REAL_TIME: false
  COLDSTART: true
  # WARMSTART_CYCLE_DIR: /glade/derecho/scratch/paddy/WARMSTART
nco:
  envir_dfv: prod
  NET_dfv: aqm
  model_ver_dfv: v7.0
  RUN_dfv: aqm
  OPSROOT_dfv: /glade/derecho/scratch/paddy/aqm_ensemble_expt/gfas_gefs2_nei_coldstart_0815
  KEEPDATA_dfv: true
workflow_switches:
  RUN_TASK_MAKE_GRID: false
  RUN_TASK_MAKE_OROG: false
  RUN_TASK_MAKE_SFC_CLIMO: false
  RUN_TASK_GET_EXTRN_ICS: true
  RUN_TASK_GET_EXTRN_LBCS: true
  RUN_TASK_NEXUS_GFS_SFC: true
  RUN_TASK_RUN_POST: true
  RUN_TASK_AQM_ICS: true
  RUN_TASK_AQM_LBCS: true
  RUN_TASK_NEXUS_EMISSION: true
  RUN_TASK_FIRE_EMISSION: true
  RUN_TASK_POINT_SOURCE: true
  RUN_TASK_PRE_POST_STAT: false
  RUN_TASK_POST_STAT_O3: false
  RUN_TASK_POST_STAT_PM25: false
  RUN_TASK_BIAS_CORRECTION_O3: false
  RUN_TASK_BIAS_CORRECTION_PM25: false
task_make_grid:
  GRID_DIR: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/fix/aqm/DOMAIN_DATA/AQM_NA_13km/
task_make_orog:
  OROG_DIR: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/fix/aqm/DOMAIN_DATA/AQM_NA_13km/
task_make_sfc_climo:
  SFC_CLIMO_DIR: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/fix/aqm/DOMAIN_DATA/AQM_NA_13km/
task_get_extrn_ics:
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_NAME_ICS: FV3GFS

  # EXTRN_MDL_SOURCE_BASEDIR_ICS: /glade/campaign/collections/rda/data/ds084.1/2020/20200815
  EXTRN_MDL_SOURCE_BASEDIR_ICS: /glade/campaign/ral/wsap/jaredlee/rrfs-cmaq/fake_gefs/2020/20200815
  EXTRN_MDL_FILES_ICS: ( gfs.mod02.0p25.2020081512.f000.grib2 )
  FV3GFS_FILE_FMT_ICS: grib2
  EXTRN_MDL_ICS_OFFSET_HRS: 0
task_get_extrn_lbcs:
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: grib2
  
  # EXTRN_MDL_SOURCE_BASEDIR_LBCS: /glade/campaign/collections/rda/data/ds084.1/2020/20200815
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: /glade/campaign/ral/wsap/jaredlee/rrfs-cmaq/fake_gefs/2020/20200815
  EXTRN_MDL_FILES_LBCS: 
    - gfs.mod02.0p25.2020081512.f006.grib2
    - gfs.mod02.0p25.2020081512.f012.grib2
    - gfs.mod02.0p25.2020081512.f018.grib2
    - gfs.mod02.0p25.2020081512.f024.grib2
    - gfs.mod02.0p25.2020081512.f030.grib2
    - gfs.mod02.0p25.2020081512.f036.grib2
    - gfs.mod02.0p25.2020081512.f042.grib2
    - gfs.mod02.0p25.2020081512.f048.grib2
    - gfs.mod02.0p25.2020081512.f054.grib2
    - gfs.mod02.0p25.2020081512.f060.grib2
    - gfs.mod02.0p25.2020081512.f066.grib2
    - gfs.mod02.0p25.2020081512.f072.grib2

  EXTRN_MDL_LBCS_OFFSET_HRS: 0
  WTIME_GET_EXTRN_LBCS: 02:00:00
task_run_fcst:
  DT_ATMOS: 180
  LAYOUT_X: 50
  LAYOUT_Y: 34
  BLOCKSIZE: 16

  # NOTE: This is a key difference in the run cycle config.
  #RESTART_INTERVAL: 6 12 24
  RESTART_INTERVAL: 24
  WTIME_RUN_FCST: 08:00:00
  QUILTING: true
  PRINT_ESMF: false

  # NOTE: This is a key difference in the run cycle config.
  DO_FCST_RESTART: true
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: 793
  USE_CUSTOM_POST_CONFIG_FILE: false
task_aqm_lbcs:
  PPN_AQM_LBCS: 24
  WTIME_AQM_LBCS: 01:00:00
task_nexus_gfs_sfc:
  NEXUS_GFS_SFC_OFFSET_HRS: 0
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
  HALO_BLEND: 0
cpl_aqm_parm:
  CPL_AQM: true
  DO_AQM_CHEM_LBCS: true
  DO_AQM_GEFS_LBCS: true
  DO_AQM_DUST: true
  DO_AQM_CANOPY: false
  DO_AQM_PRODUCT: true
  DO_AQM_SAVE_AIRNOW_HIST: false
  DO_AQM_SAVE_FIRE: false
  AQM_BIO_FILE: BELD_Norm_Area_6.0_1US3_RDS-2013-0013_MODIS_CDL_Canada.nc4
  AQM_DUST_FILE_PREFIX: FENGSHA_p8_10km_inputs
  AQM_DUST_FILE_SUFFIX: .nc
  AQM_CANOPY_FILE_PREFIX: gfs.t12z.geo
  AQM_CANOPY_FILE_SUFFIX: .canopy_regrid.nc

  DCOMINfire: /glade/campaign/ral/nsap/paddy/NOAA_fire/ensemble_alternate_fire_emissions/gfas72
  AQM_FIRE_FILE_PREFIX: Hourly_Emissions_regrid_NA_13km
  AQM_FIRE_FILE_SUFFIX: _h72.nc
  AQM_RC_FIRE_FREQUENCY: hourly

  AQM_LBCS_FILES: am4_bndy.c793.2019<MM>.v1.nc
  COMINgefs: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/GEFS_Aerosol
  AQM_GEFS_FILE_PREFIX: gfs
  AQM_GEFS_FILE_CYC: 00
  COMINemis: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/emissions/nexus

  COMINemispt: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/nei2016v1-pt/v2023-01-PT

  NEXUS_GRID_FN: grid_spec_793.nc
  NUM_SPLIT_NEXUS: 3
  # Paddy added this next line:
  # HPSS is not available from Derecho, so the model uses MERRA2 climatology instead
  FIXaqmnexus_gfs_sfc: /glade/campaign/ral/nsap/paddy/NOAA_fire/NOAA_uploads/GFS_SFC/nexus_gfs_sfc.id_1703017374_2023081512

